### ISSUE TITLE
Could not find method ikvmCompile() for arguments [file collection] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

### ISSUE THREAD

**Issue by Vad1mo** [Itiviti/gradle-ikvm-plugin#36]
i have this entry in my gradle file 

```groovy
dependencies {
  ikvmCompile files("$rootProject.projectDir/libs/mscorlib.dll")
```

and with version 2.10 I get the error:
Could not find method ikvmCompile() for arguments [file collection] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

war ikvmCompile removed?

**Comment by ngyukman** [comment]
hi, ikvmCompile is just an gradle dependencies configuration created in https://github.com/Itiviti/gradle-ikvm-plugin/blob/6faf2090636fcab58f7e3c9ca2a6ef4e3198a6d1/src/main/groovy/com/ullink/Ikvm.groovy#L87

the configuration name will depends on your task name

**Comment by Vad1mo** [comment]
I have the default task name, so I guess my task name is then  ìkvm`.
This is also correct location containing the file:  `files("$rootProject.projectDir/libs/mscorlib.dll")`

It is not clear to me what is missing.

**Comment by Vad1mo** [comment]
I found the issue, 

it should be: `ikvmcompile` instead of `ikvmCompile`

eg. 
`ikvmcompile files("$rootProject.projectDir/libs/mscorlib.dll")` 

The the readme.md should be updated to reflect that.
